modify for USG

diff --git a/ss-tproxy b/ss-tproxy
--- a/ss-tproxy
+++ b/ss-tproxy
@@ -57,9 +57,25 @@ color_yellow() {
     printf "\e[31m$*\e[0m"
 }
 
+log_info() {
+    echo "$(font_bold $(color_green '[INFO]')) $*" 1>&2
+}
+
+log_warn() {
+    echo "$(font_bold $(color_yellow '[WARN]')) $*" 1>&2
+}
+
 log_error() {
-    echo "$(font_bold $(color_yellow '[ERROR]')) $*" 1>&2
+    echo "$(font_bold $(color_red '[ERROR]')) $*" 1>&2
     exit 1
+}
+
+log_info_start() {
+    echo -n "$(font_bold $(color_green '[INFO]')) $*" 1>&2
+}
+
+log_info_end() {
+    echo "$*" 1>&2
 }
 
 is_true() {
@@ -182,7 +198,7 @@ resolve_hostname_by_dig() {
         fi
     fi
     [ "$addr_family" = '-4' ] && local dns_qtype='A' || local dns_qtype='AAAA'
-    dig +short "$dns_qtype" "$hostname" | grep -Ev '^;|\.$' | head -n1
+    dig +short "$dns_qtype" "$hostname" "@$dns_direct" | grep -Ev '^;|\.$' | head -n1
 }
 
 resolve_hostname_by_getent() {
@@ -219,7 +235,7 @@ waiting_network() {
     [ -z "$1" ] && return
     is_ipv4_address "$1" && local ping_cmd="$ping4" || local ping_cmd="$ping6"
     until $ping_cmd -nq -c1 -W1 "$1" >/dev/null; do
-        echo "waiting for network available..."
+        log_info "Waiting for network available..."
         sleep 1
     done
 }
@@ -341,6 +357,7 @@ check_config() {
 }
 
 resolve_svraddr() {
+    log_info "Resolving proxy server addresses ..."
     if is_true "$ipv4"; then
         proxy_svripv4=()
         for svraddr in "${proxy_svraddr4[@]}"; do
@@ -356,6 +373,7 @@ resolve_svraddr() {
             proxy_svripv6+=("$svripv6")
         done
     fi
+    log_info "Success."
 }
 
 update_chnlist() {
@@ -507,6 +525,7 @@ EOF
 }
 
 start_dnsserver() {
+    log_info "Starting DNS server ..."
     local dnsmasq_append_config=("${dnsmasq_conf_string[@]}")
     if is_true "$ipv4"; then
         for ((i = 0; i < ${#proxy_svraddr4[@]}; ++i)); do
@@ -579,14 +598,17 @@ EOF
     fi
 
     update_pidfile
+    log_info "Success."
 }
 
 stop_dnsserver() {
+    log_info "Stopping DNS server ..."
     kill -9 $status_dnsmasq_pid  &>/dev/null
     kill -9 $status_chinadns_pid &>/dev/null
     kill -9 $status_dns2tcp4_pid &>/dev/null
     kill -9 $status_dns2tcp6_pid &>/dev/null
     delete_pidfile
+    log_info "Success."
 }
 
 flush_dnscache() {
@@ -595,6 +617,7 @@ flush_dnscache() {
 }
 
 modify_resolvconf() {
+    log_info "Modifying resolve.conf ..."
     [ -z "$opts_overwrite_resolv" ] && return
     if is_false "$opts_overwrite_resolv"; then
         while umount /etc/resolv.conf &>/dev/null; do true; done
@@ -606,10 +629,12 @@ modify_resolvconf() {
     echo "# Generated by ss-tproxy at $(date '+%F %T')" >/etc/resolv.conf
     is_true "$ipv4" && echo "nameserver 127.0.0.1" >>/etc/resolv.conf
     is_true "$ipv6" && echo "nameserver ::1" >>/etc/resolv.conf
+    log_info "Success."
 }
 
 restore_resolvconf() {
     [ -z "$opts_overwrite_resolv" ] && return
+    log_info "Restoring resolv.conf ..."
     if is_false "$opts_overwrite_resolv"; then
         while umount /etc/resolv.conf &>/dev/null; do true; done
     else
@@ -617,25 +642,34 @@ restore_resolvconf() {
         is_true "$ipv4" && echo "nameserver $dns_direct" >>/etc/resolv.conf
         is_true "$ipv6" && echo "nameserver $dns_direct6" >>/etc/resolv.conf
     fi
+    log_info "Success."
 }
 
 start_proxy_proc() {
-    eval "$proxy_startcmd" || log_error "failed to start local proxy process, exit-code: $?"
+    log_info "Starting proxy process ..."
+    eval "$proxy_startcmd" || log_error "Failed to start local proxy process, exit-code: $?"
+    log_info "Success."
 }
 
 stop_proxy_proc() {
+    log_info "Stopping proxy process ..."
     eval "$proxy_stopcmd" &>/dev/null
+    log_info "Done."
 }
 
 enable_ipforward() {
+    log_info "Enabling IP forward ..."
     is_true "$ipv4" && set_sysctl_option 'net.ipv4.ip_forward' 1
     is_true "$ipv6" && set_sysctl_option 'net.ipv6.conf.all.forwarding' 1
+    log_info "Success."
 }
 
 disable_icmpredir() {
+    log_info "Disabling ICMP redirections ..."
     for dir in $(ls /proc/sys/net/ipv4/conf); do
         set_sysctl_option "net.ipv4.conf.$dir.send_redirects" 0
     done
+    log_info "Success."
 }
 
 delete_gfwlist() {
@@ -754,8 +788,10 @@ _flush_postrule() {
 
 flush_postrule() {
     ss_tproxy_is_started && return
+    log_info "Flusing post-rules ..."
     is_true "$ipv4" && _flush_postrule "iptables"
     is_true "$ipv6" && _flush_postrule "ip6tables"
+    log_info "Success."
 }
 
 _delete_unused_iptchains() {
@@ -782,8 +818,10 @@ _delete_unused_iptchains() {
 }
 
 delete_unused_iptchains() {
+    log_info "Deleting unused iptable chains ..."
     is_true "$ipv4" && _delete_unused_iptchains "iptables"
     is_true "$ipv6" && _delete_unused_iptchains "ip6tables"
+    log_info "Success."
 }
 
 start_iptables_pre_rules() {
@@ -1037,6 +1075,7 @@ start_iptables_redirect_mode() {
 }
 
 start_iptables() {
+    log_info "Starting iptables ..."
     is_true "$ipv4" && start_iptables_pre_rules "iptables"
     is_true "$ipv6" && start_iptables_pre_rules "ip6tables"
 
@@ -1050,6 +1089,7 @@ start_iptables() {
 
     is_true "$ipv4" && start_iptables_post_rules "iptables"
     is_true "$ipv6" && start_iptables_post_rules "ip6tables"
+    log_info "Success."
 }
 
 start() {
@@ -1062,8 +1102,8 @@ start() {
     disable_icmpredir
     restore_resolvconf
     resolve_svraddr
-    start_proxy_proc
     start_dnsserver
+    start_proxy_proc
     start_iptables
     modify_resolvconf
 
@@ -1078,8 +1118,8 @@ stop() {
     flush_iptables
     delete_chnroute
     delete_iproute2
-    stop_dnsserver
     stop_proxy_proc
+    stop_dnsserver
     check_postrule
 
     [ "$(type -t post_stop)" = 'function' ] && post_stop
@@ -1150,7 +1190,7 @@ main() {
     done
 
     if [ "${#arguments[@]}" -eq 0 ]; then
-        echo "$(color_yellow "Missing necessary options")"
+        log_warn "Missing necessary options"
         help
         return 1
     fi
@@ -1172,7 +1212,7 @@ main() {
         update-chnroute) update_chnroute;;
         v*)              version;;
         h*)              help;;
-        *)               echo "$(color_yellow "Unknown option: ${arguments[0]}")"; help; return 1;;
+        *)               log_warn "Unknown option: ${arguments[0]}"; help; return 1;;
     esac
     return 0
 }
